### ISSUE TITLE
Cake.AWS.ElasticBeanstalk package ID in metadata differs from NuGet package ID on casing

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/website#1401]
I noticed this earlier today whilst working on displaying the TFMs:

| Package ID on website | Package ID on nuget.org |
|:---:|:---:|
| [Cake.**AWS**.ElasticBeanstalk](https://github.com/cake-build/website/blob/af4c5a33f6cd119b23ab4cd613c88340b22a4e74/extensions/Cake.Aws.ElasticBeanstalk.yml#L2-L3) | [Cake.**Aws**.ElasticBeanstalk](https://www.nuget.org/packages/Cake.Aws.ElasticBeanstalk/) |

Is this on purpose or should we update the YAML metadata?
If we do rename, are there any consequences for AddinDisco? /cc @Jericho

**Comment by Jericho** [comment]
The spelling with upper case `AWS` is the way the YAML file was manually created back in May 2017 and the AddinDiscoverer does not update this value. Fun fact: the [GitHub URL](https://github.com/mathieukempe/Cake.AWS.ElasticBeanstalk) for this addin uses the upper case spelling.

I can't think of any particular consequence as far as the discoverer is concerned. I would check with the addin author, they may prefer one spelling rather than the other.

As far as I can tell, the `Name` in this YAML file hasn't changed for 3 1/2 years so I'm curious: is this situation now causing a problem that you feel needs to be solved?

**Comment by augustoproiete** [comment]
Thanks @Jericho that explains the difference in casing then.

The only situation where I saw a problem so far was when I tried to generate a list of links to each addin metadata file (for creating a table in one of the issues I worked on), where I did something like `$"https://github.com/cake-build/website/blob/master/extensions/{PackageIDFromMetadata}.yml"`, and when I tested the links, I got a 404 on this one because GitHub is case sensitive:

- [https://github.com/cake-build/website/.../extensions/Cake.**Aws**.ElasticBeanstalk.yml](https://github.com/cake-build/website/blob/af4c5a33f6cd119b23ab4cd613c88340b22a4e74/extensions/Cake.Aws.ElasticBeanstalk.yml) (OK)
- [https://github.com/cake-build/website/.../extensions/Cake.**AWS**.ElasticBeanstalk.yml](https://github.com/cake-build/website/blob/af4c5a33f6cd119b23ab4cd613c88340b22a4e74/extensions/Cake.AWS.ElasticBeanstalk.yml) (404)

It's an edge case for sure, but given that we have separate properties for each addin (`Name` and `NuGet`), I think it makes sense to update the `NuGet` property to match what's on nuget.org and resolve the above and avoiid other possible issues we may get if we start building the website on Linux where things are case-sensitive.

![image](https://user-images.githubusercontent.com/177608/104814262-4d8a4780-57e4-11eb-8107-a260e8812916.png)

I'll send a PR shortly.
