### ISSUE TITLE
Passing wildcard to MSBuild settings?

### ISSUE THREAD

**Issue by sahilkhan99** [cake-build/website#145]
Hi,
Is it possible to build specific project files under .sln project and also can exclude one single project ?

The example documentation has 'Run-Unit-tests' task using Nunit3 with wildcard characters and If I use the same thing for the MSBuild settings the build gives an error.

The below one works fine 
```
Task("Run-Unit-Tests")
    .IsDependentOn("Build")
    .Does(() =>
{
    NUnit3("./**/bin/" + configuration + "/*.Tests.dll", new NUnit3Settings {
        NoResults = true
        });
}); 
```
Issue , it fails here
```
Task("Build")
    .IsDependentOn("Restore-NuGet-Packages")
    .Does(() =>
{
    if(IsRunningOnWindows())
    {
      // Use MSBuild
    
	  MSBuild("./CakeApp/**/*.csproj", settings =>
		settings.SetConfiguration(configuration));
    }
    else
    {
      // Use XBuild
      XBuild(solutionDirPath, settings =>
        settings.SetConfiguration(configuration));
    }
});
```

Time Elapsed 00:00:00.38
An error occured when executing task 'Build'.
Error: Illegal characters in directory path (*).
Parameter name: path
PS C:\dev\CakeApp>

Bascially I'm looking to build few projects only in the solution. is it possible?

Many thanks.
Irfan

**Comment by devlead** [comment]
You can't pass a globber pattern directly to the `MSBuild` alias, but Cake does indeed have globbing support via the `GetFiles` aliases, so what you can do is something like below:

```cake
    var projects  = GetFiles("./**/*.csproj");
    // Build all solutions.
    foreach(var project in projects)
    {
        Information("Building {0}", solution);
        MSBuild(project, settings =>
            settings.SetPlatformTarget(PlatformTarget.MSIL)
                .WithProperty("TreatWarningsAsErrors","true")
                .WithTarget("Build")
                .SetConfiguration(configuration));
    }
```

You can include/exclude by combining two `GetFiles` together like below using `-` or `+` operator:
```cake
var projects  = GetFiles("./**/*.csproj") - GetFiles("./**/*Common*.csproj");
```

**Comment by gep13** [comment]
@sahilkhan99 for future reference, the issues list here on this repo is really intended for issues/problems/questions with that Cake website at http://cakebuild.net/.  Your question would have been better suited over on the Cake repo here https://github.com/cake-build/cake, or as a question on our Gitter chat room here: https://gitter.im/cake-build/cake, or as a question tagged with `cakebuild` on StackOverflow: http://stackoverflow.com/questions/tagged/cakebuild.

Out of interest, so that we can improve our messaging, what was it that brought you to this repo to ask your question?

Thanks for reaching out though, hope you are enjoying using Cake, and that @devlead answer above helps you out.

**Comment by sahilkhan99** [comment]
Hi @devlead , Thank you for the answer. very helpful. I'll create a PR with this example so that other people can benefit from your answer.
 
@gep13, thank you for guiding me. I completely agree and I have chosen the wrong repo to ask this question. I clearly did not see there are 2 repos (website and cake). When I went on to the http://cakebuild.net/docs/tutorials/getting-started, I saw the edit on repo link and I thought was only available repo for cake. 

I'll make sure next i'll ask more relevant question with specific repository.

Thank you.
