### ISSUE TITLE
Rate limiting contributor list 

### ISSUE THREAD

**Issue by pascalberger** [cake-build/website#2243]
[Contributor list](https://cakebuild.net/community/thanks/#contributors) is currently retrieved client side where we sometimes run into rate limiting issues.

We could make authenticated calls to get a higher rate limit or create the list server side

**Comment by Jericho** [comment]
If it can be helpful: the AddinDiscoverer could discover the list of contributors and generate a XML/JSON/YAML file (or any other format deemed more convenient) on every run (which currently is twice a day). An issue would be opened and a PR submitted whenever a new contributor is discovered giving you the ability to review and approve the changes. The client side code in the `community/thanks` page would need to be modified to consume the XML/JSON/YAML file instead of querying GitHub though.

**Comment by pascalberger** [comment]
@Jericho That sounds like a good idea to me. 

A YAML file would make sense, like we already use for extensions or maintainers. The YAML should contain the following fields for every contributor:

- GitHub user name
- URL to profile picture
