### ISSUE TITLE
Nuget aliases not on the dsl site

### ISSUE THREAD

**Issue by gep13** [cake-build/website#244]
@stefandevo commented on [Wed Jan 11 2017](https://github.com/cake-build/cake/issues/1443)

On http://cakebuild.net/dsl the Nuget aliases are missing from the left navigation bar.
Basically there is no link to http://cakebuild.net/api/cake.common.tools.nuget and http://cakebuild.net/api/cake.common.tools.nuget/bdfa6572

**Comment by gep13** [comment]
@stefandevo, I suspect I know what the issue is here.  There are both nuget aliases and aliases from the Extended NuGet addin, and they are getting combined.

We are almost at the point of releasing a new version of the website, which I think will correct this issue.

Thanks for reporting it though!

**Comment by stefandevo** [comment]
Ok thanks!

**Comment by devlead** [comment]
@daveaglick still seem to be an issue with the new site.

**Comment by daveaglick** [comment]
This seems like it's going to be a problem anytime there are both built-in and addon aliases that specify the same category. I see these possible solutions:
- Make the website know about the NuGet aliases and which ones are built-in and which ones aren't. Not a fan of this approach since it doesn't solve the underlying problem.
- Make the documentation aware of the default `Cake.Common.*` namespace and always place aliases in classes in that namespace under the built-in section.
- Give either the addin or the built-in alias class a different category ("NuGet" and "NuGet Extended" for example).
- Add support for indicating whether an alias class is built-in or not to the category attribute.

The last two solutions require changes to the underlying Cake code and/or to the addin code, so the fixes wouldn't be immediate (they wouldn't take effect until the next release). I'll see what I can do about getting the website to be aware of the `Cake.Common` namespace and if that resolves the problem.

**Comment by devlead** [comment]
Would it be possible to duplicate? If both builtin and addin show in both places? And then  on the   category page group by assembly?

**Comment by daveaglick** [comment]
Maybe, but that still presents a few problems:
- The summary for the built-in category is different than the summary for the addin category. If both sets show on both pages, figuring out which summary to show means we still have to treat the categories differently on the index page.
- Would we do that for every category? If so, does it make sense to continue having a sidebar with the distinction between built-in and addin categories? Maybe the sidebar should just show overall categories and we can make the distinction between the two just on the category page between aliases?

The more I think about it, the more that last point makes sense. Alias categories aren't intrinsically "built-in" or "addin" - that seems like more of an implementation detail. NuGet aliases are NuGet aliases are NuGet aliases. And the URLs would still work since they treat all categories equally already. There's also the issue of multiple add-ins eventually using conflicting categories.

Unless there's an objection, I'll run with this:
- Remove the "built-in" vs. "addin" distinction from the Reference/DSL sidebar and from the Reference/DSL category index page.
- Use the summary for a category from the core/common source code first (if there is one) and then fallback to the summary from an external library if needed.
- On the page for each category group aliases by assembly (or core/common) and indicate for non core/common aliases that they come from an addin. I'll also be able to use the specific summary for each category definition here (in the case that there are more than one).

This is quite a bigger change than I was anticipating since it totally reworks the Reference/DSL pages. Might take a few days to get right...

**Comment by devlead** [comment]
Don't think this is a blocker as it's an existing bug on old page too. So we can discuss this further until we get consensus around a final solution.

Main objective is to make it clear which aliases ship with cake and which need an addin to work. But initially perhaps built in should trump addin in menu?

**Comment by daveaglick** [comment]
For now I made it so that if there is a category collision, the category shows up under *both* Built-It and Addin sections. Then within the summary information for each alias, there is additional text indicating if the alias is part of an addin and if so, which assembly (along with a link). This strikes me as a good middle ground.

Depending on how much everyone likes the little note about the alias being part of an addin in the summary, I could see this change resolving the issue if we followed-up by just removing the Built-In/Addin category distinction altogether and just relied on the text in the summary of each alias within the category to indicate if it's from an addin and which one.

**Comment by stefandevo** [comment]
I think this works for now! Thanks. 
And yes, the note in the summary should better be removed.

**Comment by gep13** [comment]
@cake-build/team so here is an example...

http://develop.cakebuild.net/api/Cake.ExtendedNuGet/ExtendedNuGetAliases/ACE455D3

![image](https://cloud.githubusercontent.com/assets/1271146/22021922/a0fd6f20-dcb7-11e6-9223-0493371fbd0b.png)

Personally, I think this makes a lot of sense.  i.e. all aliases that are related to each other, i.e. NuGet are in one place, and once selected, it shows whether this is built-in, or comes from an addin.  👍 from me.

**Comment by devlead** [comment]
@gep13 agree 👍

**Comment by pascalberger** [comment]
While currently looking at http://cakebuild.net/dsl/git/ a note is displayed that content is part of the `Cake.GitPackager` addin, even though some of it is also from `Cake.Git`. Also summary only points to `Cake.GitPackager`.

I assume this is the same issue with multiple addins sharing the same category?

**Comment by daveaglick** [comment]
@pascalberger Good catch - we're consolidating aliases from multiple addins that use the same category at this point, but the info text at the top is still only showing the first one. That info text box needs to be adjusted to show all the addins that are presented in the alias list.

**Comment by pascalberger** [comment]
Currently categories on the reference page are splitted in "Built-In" and "Addins". As a user my main interested is to find an existing functionality, if it is in an addin or built-in most often is not my primary concern in this case.
Regarding this, wouldn't it be clearer to have just a single category listing in the left navigation sidebar, and then for each category three views rendered:

- One containing only built-in functionality
- One containing only functionality from addins
- One containing built-in functionality and functionality from addins

On the views a link/control could be placed to switch between the views (something like `[x] Show built-in [x] Show from addins`).

This would also solve the different problems existing with the current layout where built-in stuff is mixid with functionality from aliases.

**Comment by pascalberger** [comment]
Closing this and have created https://github.com/cake-build/website/issues/1078 for remaining issues/suggestions
