### ISSUE TITLE
Layout broken

### ISSUE THREAD

**Issue by pascalberger** [cake-build/website#353]
Layout for alias summary is broken: http://cakebuild.net/dsl/docfx/

![image](https://cloud.githubusercontent.com/assets/2190718/25652713/dcf83912-2fe9-11e7-885e-327f2428ee28.png)

I assume the reason are the obsolete comments with a quite long `see cref`.

**Comment by gep13** [comment]
@daveaglick perhaps another one for the pairing session we have been speaking about.

**Comment by daveaglick** [comment]
It's that third one down that's breaking it, there's no space for a wrap point. Should be a simple CSS change to wrapping behavior.

@gep13 Yep, let's add it to the list. We can apply a temporary fix to the Cake site and then I'll permanently fix upstream in Wyam. Next week may be a good time to pair since I'll be out of the office - I'll DM you about times soon.

**Comment by pascalberger** [comment]
Showing aliases for addins uses the same code and has the same issue:

![image](https://user-images.githubusercontent.com/2190718/97094825-d3b94680-1658-11eb-83fd-4ea1af7d2967.png)
