### ISSUE TITLE
Extra </string> in code sample for setting up a new project

### ISSUE THREAD

**Issue by gep13** [cake-build/website#37]
Here:

http://cakebuild.net/docs/tutorials/setting-up-a-new-project

There seems to be an extra `</string>` at the end of the code sample:

![image](https://cloud.githubusercontent.com/assets/1271146/11554696/3f7f2f36-9992-11e5-9237-ece27f2af63e.png)

Which I think is caused by the `<string>` being passed as an argument on the first line.

Is this due to the syntax highlighting tool that we are using?

**Comment by marking** [comment]
This is due to the use of HtmlAgilityPack in ContentProcessor.cs (around line 39) which is used to parse the md file and replace the md code blocks with html code blocks with a specific class attribute to allow for the nice code formatting.

Once the .md file is loaded, the `<bool>`, `<string>` etc., items are interpreted by HtmlAgilityPack as opened tags that need to be closed, so it closes them.

I've fiddled with some of the configuration settings in HtmlAgilityPack, but I cannot get it to leave those 'tags' open.

it might be worth looking at [Mads' Web Essentials Markdown processor](https://github.com/madskristensen/WebEssentials2015/tree/master/EditorExtensions/Markdown) to see if a similar approach can be used.

**Comment by jnm2** [comment]
This also plagues the [Usage Information](http://cakebuild.net/docs/cli/usage) page:

> Can be accessed from the script with the Argument alias:
> 
> ```c#
> Argument<bool>("showstuff", false);
> </bool>
> ```

For Markdown processing I'd also recommend [Markdig](http://xoofx.com/blog/2016/06/13/implementing-a-markdown-processor-for-dotnet/) by @xoofx now.

**Comment by gep13** [comment]
@jnm2 I believe that this will get corrected once @daveaglick announces his surprise 😄

**Comment by daveaglick** [comment]
Can confirm this is resolved.
