### ISSUE TITLE
Alias / API documentation for Cake.Svn missing

### ISSUE THREAD

**Issue by pascalberger** [cake-build/website#427]
Some time ago I added the Cake.Svn addin (https://github.com/cake-build/website/pull/421) and it is added to the addin list [here](https://cakebuild.net/addins/subversion/), but its missing from reference and API. Any idea why?

**Comment by daveaglick** [comment]
Because the NuGet package is listed as prerelease, we have to add a flag to the `Cake.Svn.yml` file to tell the website build script to allow prerelease packages for this addin when fetching the package and XML documentation. I went ahead and opened a PR for this.

**Comment by pascalberger** [comment]
@daveaglick These are the aliases in version 1.0: https://github.com/cake-contrib/Cake.Svn/blob/master/src/Cake.Svn/SvnAliases.Export.cs#L21 inside a partial class with the `CakeAliasCategory` for the class [here](https://github.com/cake-contrib/Cake.Svn/blob/master/src/Cake.Svn/SvnAliases.cs#L10). I think having the `CakeAliasCategory` attribute in partial classes should work, as if i remember correctly, also other addins are doing this

**Comment by daveaglick** [comment]
Yeah, partial classes should be fine - was just doing some bug fixing on that scenario the other day too. I've also confirmed the correct NuGet package is downloaded without needing the prerelease flag. Still digging (but have to leave for the day so might not get back to it until this weekend).

**Comment by daveaglick** [comment]
FYI - spent some significant time this weekend looking at this. Ended up getting sidetracked into other unrelated issues with Wyam, but there's definitely something strange going on here that's not at all related to the prerelease flag. Wyam sees and loads the assembly but for some reason it's not adding anything to the compilation. I'm continuing to investigate, but I'm going to close the PR since the prerelease flag is not the issue.

**Comment by daveaglick** [comment]
Found the problem. The YAML file for this addin uses "Cake.Svn.dll" as the assembly, but it should actually be "/**/Cake.Svn.dll" since the search for the assembly file starts at the root of the package folder structure (to account for alternate packing strategies, multi-targeting, etc.)

PR incoming to correct this and any other addin YAML files with the same problem (I think there might be a couple others).
