### ISSUE TITLE
Dedicated intellisense page

### ISSUE THREAD

**Issue by jnm2** [cake-build/website#493]
Do you have a page about setting up intellisense yet? Right now the relevant information seems to be spread across two blog posts. (https://cakebuild.net/blog/2017/11/intellisense-vscode and https://cakebuild.net/blog/2018/02/intellisense-improvements).

I was expecting to find the full set of instructions under https://cakebuild.net/docs/editors and perhaps linked from the homepage or somewhere people would see it.

It makes sense to talk about intellisense before people pick from the list of editors, too, because knowing that only one editor does Cake intellisense will inform their choice. :smiley:

**Comment by missfelic** [comment]
Can I help you with this? :D

**Comment by pascalberger** [comment]
@missfelic Would be great. To start with it would be nice to have documentation for IntelliSense support directly on https://cakebuild.net/docs/editors/vscode, instead of being spread into the two blog posts mentioned in the issue. Wording form blog post needs to be adopted in some cases to fit to the website and some information might be outdated.

Based on this we could add an overview page later on https://cakebuild.net/docs/editors/ to show which editor supports which capability (in a table).

**Comment by pascalberger** [comment]
See also [discussion on Gitter](https://gitter.im/cake-build/cake?at=5f74d1cdd5337c048e02eb57)
